# Generated by Django 2.2.7 on 2019-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='checkIn',
            field=models.DateTimeField(auto_now=True, verbose_name='checkIn time'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='checkOut',
            field=models.DateTimeField(auto_now=True, verbose_name='checkOut time'),
        ),
    ]
