# Generated by Django 2.2.7 on 2019-11-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_auto_20191120_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateTimeField(auto_now=True, verbose_name='checkIn time')),
                ('checkOut', models.DateTimeField(auto_now=True, verbose_name='checkOut time')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Host')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='VisitorEntry',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.User'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.User'),
        ),
    ]
