# Generated by Django 2.2.7 on 2019-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20191120_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkOut',
            field=models.DateTimeField(null=True, verbose_name='checkOut time'),
        ),
    ]
